import {
    DEVICE_ID,
    NOTIFY_CHARACTERISTIC_UUID,
    SERVICE_UUID,
    WRITE_CHARACTERISTIC_UUID,
} from '@env';
export const BleConstants = {
    SERVICE_UUID,
    NOTIFY_CHARACTERISTIC_UUID,
    WRITE_CHARACTERISTIC_UUID,
    DEVICE_ID,
    RESPONSE_TIMEOUT: 10000,
};
